### ISSUE TITLE
此方法已失效

### ISSUE THREAD

**Issue by ZeroQing89** [xiaou61/XiaoYuanKousuan#1]
此方法已失效，在经历刚刚的热更之后，数据都加密了

**Comment by Sawyer-Z** [comment]
> 此方法已失效，在经历刚刚的热更之后，数据都加密了

加密的是pk场，不是练习场

**Comment by ZeroQing89** [comment]
> > 此方法已失效，在经历刚刚的热更之后，数据都加密了
> 
> 加密的是pk场，不是练习场

但是刚才我获取到的练习场响应也是乱码的

**Comment by chengnan049** [comment]
![Screenshot_2024-10-11-17-01-42-95_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://github.com/user-attachments/assets/10e284d3-0537-427a-9d4a-495b50c13834)

**Comment by ZeroQing89** [comment]
> ![Screenshot_2024-10-11-17-01-42-95_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://private-user-images.githubusercontent.com/46060083/375694615-10e284d3-0537-427a-9d4a-495b50c13834.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mzc2NTIsIm5iZiI6MTcyODYzNzM1MiwicGF0aCI6Ii80NjA2MDA4My8zNzU2OTQ2MTUtMTBlMjg0ZDMtMDUzNy00MjdhLTlkNGEtNDk1YjUwYzEzODM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNGVhMTNiNWNjYTBkZTQ0ZDQyMmJiMWQwNGM5MzNkYjc2MDdlMDA5MmQ4YWRlMjgxOThkMWJhNGQ0MDFmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7We7urpOGdO94VFfy702roWRiV-BVaicqU6oPDWB7vA)

啊？刚才我抓的是乱码的了

**Comment by chengnan049** [comment]
可能太多了，看岔了

**Comment by ZeroQing89** [comment]
> 可能太多了，看岔了

离全加密估计也不远了

**Comment by xiaou61** [comment]
练习还有用，但是不知道什么时候会加密上
